### ISSUE TITLE
UNIX Socket to roslibrist

### ISSUE THREAD

**Issue by Akumar201** [Carter12s/roslibrust#74]
Hi, I would like to know has anyone tried data transfer from UNIX Socket to roslibrust , like making a subscriber using roslibrust ? 
I want to transfer data from an application to roslibrust in the same machine and then make a publisher to transfer to another system. Any suggestion would be much appreciated. My basic Idea now is to create a UNIX Socket and transfer data to a subscriber in roslibrust within the same system and then transfer the data to another system making a publisher.

**Comment by ssnover** [comment]
All of the generated roslibrust message types derive `serde::{Serialize, Deserialize}`, so you should be able to trivially serialize them to any wire format that has a serde implementation. Since roslibrust uses async, I recommend trying `tokio`, which has an async wrapper for UNIX sockets, as well as TCP/UDP sockets/streams.

**Comment by Akumar201** [comment]
Thank You
